language: generic
dist: trusty
sudo: required

os:
    - linux
    - osx

install:
    case $TRAVIS_OS_NAME in
    osx)
    travis_retry brew update &&
    travis_retry brew install coq ;;
    linux)
    travis_retry wget https://raw.github.com/ocaml/opam/master/shell/opam_installer.sh -O - | sh -s /usr/local/bin &&
    travis_retry opam install coq -y &&
    travis_retry eval $(opam config env) ;;
    esac
script:
    travis_retry make -j
